name: build-code

on:
  push:
    branches:
      - 'main'
      - 'feature/**'
    tags:
      - 'v**'
  workflow_call:

jobs:
  build-code:
    runs-on: ubuntu-latest
    env:
      DOCKER_CLI_EXPERIMENTAL: "enabled"
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: magnetikonline/action-golang-cache@v4
        with:
          go-version-file: go.mod
      - name: Set up Go cover
        working-directory: .
        run: go get golang.org/x/tools/cmd/cover
      - name: Test
        working-directory: .
        run: make test
